version: '3.8'

volumes:
  redis_data:

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: religious-notifs-app
    ports:
      - 4000:4000
    env_file:
      - .env.production
    # depends_on:
    #   - redis

  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   env_file:
  #     - .env.production
  #   command:
  #     - /bin/sh
  #     - -c
  #     - redis-server --save 60 1 --loglevel warning --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
  #   volumes:
  #     - redis_data:/data
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 30s
  #     timeout: 3s
  #     retries: 5
