import { OperationType } from '@prisma/client';

export const ICELL_OPERATIONS: Record<string, OperationType> = {
  SN: 'SUBSCRIPTION',
  ES: 'SUBSCRIPTION',
  YC: 'RENEWAL',
  YR: 'RENEWAL',
  RR: 'RENEWAL',
  GR: 'RENEWAL',
  SR: 'RENEWAL',
  YU: 'UNSUBSCRIPTION',
  ER: 'UNSUBSCRIPTION',
  YD: 'UNSUBSCRIPTION',
  PCI: 'UNSUBSCRIPTION',
  ACI: 'UNSUBSCRIPTION',
  GCI: 'UNSUBSCRIPTION',
  SCI: 'UNSUBSCRIPTION',
  BCI: 'UNSUBSCRIPTION',
  PCE: 'UNSUBSCRIPTION',
  ACE: 'UNSUBSCRIPTION',
  GCE: 'UNSUBSCRIPTION',
  SCE: 'UNSUBSCRIPTION',
  BCE: 'UNSUBSCRIPTION',
};
